### ISSUE TITLE
AttributeError: module 'mistree' has no attribute 'GetMST'

### ISSUE THREAD

**Issue by Ameliecc** [meyerls/PC-Skeletor#12]
Current volume ratio 0.0045762590683944325. Contraction weights 2048.0. Attraction weights 1012.7767136646321. Progress LBC:  45%|████▌     | 9/20 [00:10<00:12,  1.11s/it]
Traceback (most recent call last):
  File "D:\pc-skeletor-main\example_tree.py", line 21, in <module>
    lbc.extract_topology()
  File "D:\pc-skeletor-main\pc_skeletor\laplacian.py", line 288, in extract_topology
    self.skeleton_graph = self.__extract_skeletal_graph(skeletal_points=skeleton_points)
  File "D:\pc-skeletor-main\pc_skeletor\laplacian.py", line 242, in __extract_skeletal_graph
    _, _, _, _, edge_index, _ = extract_mst(points=skeletal_points)
  File "D:\pc-skeletor-main\pc_skeletor\laplacian.py", line 236, in extract_mst
    mst = mist.GetMST(x=points[:, 0], y=points[:, 1], z=points[:, 2])
AttributeError: module 'mistree' has no attribute 'GetMST'

**Comment by meyerls** [comment]
Hi @Ameliecc,

what python version are you using? What version of mistree is installed on your device?

**Comment by albertpaolobugayong** [comment]
I was able to get it to install by installing from source, thank you for the recent update :)

**Comment by yashreadytobox** [comment]
I am getting a similar issue with python 3.9 numpy version 1.26.0, on windows 11 and version of mistree===1.2.1
