### ISSUE TITLE
I encountered an error while running the SLBC example program

### ISSUE THREAD

**Issue by cyxin-art** [meyerls/pc-skeletor#20]
Traceback (most recent call last):
  File "C:\Users\caoyouxiang\Desktop\learning\findpoint\11111.py", line 37, in <module>
    lbc = SLBC(point_cloud=pcd,
  File "E:\anaconda\envs\myenv\lib\site-packages\pc_skeletor\laplacian.py", line 444, in __init__
    self.trunk = self.trunk.voxel_down_sample(down_sample)
AttributeError: 'SLBC' object has no attribute 'trunk'

**Comment by meyerls** [comment]
Hm, the trunk and branch pcd should be init in LaplacianBasedContractionBase.

Did you run the example_tree.py file? Could you please check what type pcd_trunk is (it should be of type open3d point cloud)?

**Comment by meyerls** [comment]
Closed due to inactivity
